name: knowledge_assistant_uts
description: A new Flutter project for Mobile Programming 2 UTS.
# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Sesuaikan dengan versi Dart SDK Anda

dependencies:
  flutter:
    sdk: flutter
  
  # Dependency untuk State Management (Penyempurna Nilai UTS)
  provider: ^6.1.1 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is included with your application, so that you can use the Icons class without importing anything.
  uses-material-design: true

  # Untuk bagian assets: (Jika Anda ingin menambahkan gambar atau font kustom, Anda bisa uncomment dan atur di sini)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic